[package]
name = "bdk_kyoto"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", default-features = false, features = ["full"] }
tracing = "0.1"

[dependencies.bdk_chain]
path = "../bdk/crates/chain"

[dependencies.kyoto]
#git = "https://github.com/rustaceanrob/kyoto"
path = "../kyoto"

[dev-dependencies]
anyhow = "1.0"
bdk_wallet = { path = "../bdk/crates/wallet" }
bdk_file_store = { path = "../bdk/crates/file_store" }
bdk_persist = { path = "../bdk/crates/persist" }
tracing-subscriber = "0.3"

[[example]]
name = "signet"

[[example]]
name = "wallet"
