[package]
name = "bdk_kyoto"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk_chain = { version = "0.16.0" }
tokio = { version = "1.0", default-features = false, features = ["full"] }
tracing = "0.1"

[dependencies.kyoto]
git = "https://github.com/rustaceanrob/kyoto"

[dev-dependencies]
anyhow = "1.0"
bdk_wallet = { version = "1.0.0-alpha.13" }
tracing-subscriber = "0.3"

[[example]]
name = "signet"

[[example]]
name = "wallet"
