[package]
name = "bdk_kyoto"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", optional = true }

[features]
default = ["trace"]
trace = ["tracing", "tracing-subscriber"]

[dependencies.kyoto]
git = "https://github.com/rustaceanrob/kyoto"
rev = "a3c7701b175f49d0e72d3fff71b07c7522353e9a"

[dependencies.bdk_wallet]
version = "1.0.0-alpha.13"

[dev-dependencies]
tokio = { version = "1", features = ["full"], default-features = false }
anyhow = "1.0"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }


[[example]]
name = "signet"

[[example]]
name = "wallet"

