[package]
name = "bdk_kyoto"
version = "0.1.0"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
bdk_chain = { version = "0.19.0" }
kyoto-cbf = { version = "0.2.0" }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", optional = true }

[dependencies.bdk_wallet]
version = "1.0.0-beta.4"
optional = true

[features]
default = ["trace", "wallet"]
trace = ["tracing", "tracing-subscriber"]
wallet = ["bdk_wallet"]

[dev-dependencies]
tokio = { version = "1.37", features = ["full"], default-features = false }
anyhow = "1.0"
bdk_testenv = "0.8.0"
tempfile = "3.12.0"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }


[[example]]
name = "signet"

[[example]]
name = "wallet"
required-features = ["wallet", "trace"]
