[package]
name = "bdk_kyoto"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", optional = true }

[dependencies.kyoto]
git = "https://github.com/rustaceanrob/kyoto"
rev = "3ac764e52c361a5fec61f151b0e21cf2dd0326d2"

[dependencies.bdk_wallet]
version = "1.0.0-beta.1"

[features]
default = ["trace"]
trace = ["tracing", "tracing-subscriber"]

[dev-dependencies]
tokio = { version = "1", features = ["full"], default-features = false }
anyhow = "1.0"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }


[[example]]
name = "signet"

[[example]]
name = "wallet"

