[package]
name = "bdk_kyoto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.0", default-features = false, features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.kyoto]
git = "https://github.com/rustaceanrob/kyoto"
rev = "73d841f761e96a2dd0cb2541200825ff8311266d"

[dependencies.bdk_wallet]
version = "1.0.0-alpha.13"

[[example]]
name = "signet"

[[example]]
name = "wallet"
